// /*
// ------------------------------------------------
// Generated by Cradle 2.0.2.0
// https://github.com/daterre/Cradle
//
// Original file: Content.html
// Story format: Harlowe
// ------------------------------------------------
// */
//
// using System.Collections;
// using System.Collections.Generic;
// using UnityEngine;
// using Cradle;
// using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
// using Cradle.StoryFormats.Harlowe;
//
// public partial class @Content: Cradle.StoryFormats.Harlowe.HarloweStory
// {
// 	#region Variables
// 	// ---------------
//
// 	public class VarDefs: RuntimeVars
// 	{
// 		public VarDefs()
// 		{
// 		}
//
// 	}
//
// 	public new VarDefs Vars
// 	{
// 		get { return (VarDefs) base.Vars; }
// 	}
//
// 	// ---------------
// 	#endregion
//
// 	#region Initialization
// 	// ---------------
//
// 	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;
//
// 	@Content()
// 	{
// 		this.StartPassage = "Empty";
//
// 		base.Vars = new VarDefs() { Story = this, StrictMode = true };
//
// 		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };
//
// 		base.Init();
// 		passage1_Init();
// 		passage2_Init();
// 		passage3_Init();
// 		passage4_Init();
// 	}
//
// 	// ---------------
// 	#endregion
//
// 	// .............
// 	// #1: HelloWorld
//
// 	void passage1_Init()
// 	{
// 		this.Passages[@"HelloWorld"] = new StoryPassage(@"HelloWorld", new string[]{  }, passage1_Main);
// 	}
//
// 	IStoryThread passage1_Main()
// 	{
// 		yield return text("What would you like to do?");
// 		yield return lineBreak();
// 		yield return link("Talk to the creatures", "Talk to the creatures", null);
// 		yield return lineBreak();
// 		yield return link("Walk down the ramp", "Walk down the ramp", null);
// 		yield break;
// 	}
//
//
// 	// .............
// 	// #2: Talk to the creatures
//
// 	void passage2_Init()
// 	{
// 		this.Passages[@"Talk to the creatures"] = new StoryPassage(@"Talk to the creatures", new string[]{  }, passage2_Main);
// 	}
//
// 	IStoryThread passage2_Main()
// 	{
// 		yield return text("You talk to the creatures.");
// 		yield break;
// 	}
//
//
// 	// .............
// 	// #3: Walk down the ramp
//
// 	void passage3_Init()
// 	{
// 		this.Passages[@"Walk down the ramp"] = new StoryPassage(@"Walk down the ramp", new string[]{  }, passage3_Main);
// 	}
//
// 	IStoryThread passage3_Main()
// 	{
// 		yield return text("You walk down the ramp.");
// 		yield break;
// 	}
//
//
// 	// .............
// 	// #4: Empty
//
// 	void passage4_Init()
// 	{
// 		this.Passages[@"Empty"] = new StoryPassage(@"Empty", new string[]{  }, passage4_Main);
// 	}
//
// 	IStoryThread passage4_Main()
// 	{
// 		yield break;
// 	}
//
//
// }